server {
    listen 80;

    client_max_body_size 50M;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # La magia: Nginx ahora sabe exactamente a qué máquina interna pegarle
        proxy_pass http://srv-d6oe7c14tr6s73bn4ikg:8080;
    }
}
